# Generated by Django 5.1.10 on 2026-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bus_firstname_bus_lastname_bus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
