# Generated by Django 5.1.6 on 2025-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
