# Generated by Django 5.1.10 on 2025-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ticket_email_ticket_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
