# Generated by Django 5.1.10 on 2025-10-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bus_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='level',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
