# Generated by Django 5.1.10 on 2025-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc',
            name='side',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
