# Generated by Django 5.1.10 on 2025-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sc_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
