# Generated by Django 5.1.10 on 2025-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bus_firstname_bus_lastname_bus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
