# Generated by Django 5.1.10 on 2025-10-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bus_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc',
            old_name='user_permissions',
            new_name='sc_permissions',
        ),
        migrations.AddField(
            model_name='sc',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sc',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sc',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
