# Generated by Django 5.1.10 on 2025-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_user_permissions_sc_sc_permissions_sc_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sc',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
