# Generated by Django 5.1.10 on 2025-10-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_sc_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sc',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='sc',
            old_name='lname',
            new_name='lastname',
        ),
    ]
