# Generated by Django 5.1.10 on 2025-11-04 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0013_rename_fname_sc_firstname_rename_lname_sc_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registered_time', models.DateTimeField(auto_now_add=True)),
                ('service_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='service_fee_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='service_fee_permissions_set', to='auth.permission')),
            ],
        ),
    ]
