# Generated by Django 5.1.10 on 2025-11-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
