# Generated by Django 5.1.10 on 2025-11-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_ticket_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='plate_no',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='side_no',
        ),
    ]
