# Generated by Django 5.1.10 on 2025-11-23 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0016_remove_worker_plate_no_remove_worker_side_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registered_time', models.DateTimeField(auto_now_add=True)),
                ('depcity', models.CharField(max_length=100)),
                ('descity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('kilometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plate_no', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='activate_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='activate_permissions_set', to='auth.permission')),
            ],
        ),
    ]
