# Generated by Django 5.1.10 on 2025-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
