# Generated by Django 5.1.10 on 2025-11-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_route_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activate',
        ),
    ]
