# Generated by Django 5.1.10 on 2025-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_delete_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
